global:
  command-timeout-seconds: 300

docker:
  host: unix:///var/run/docker.sock

slack:
- name: ClockworkSoul
  api-token: xoxb-318612539623-512030882149-I3JUlQSw30088hMU7fDQsScO
  icon-url: https://emoji.slack-edge.com/T025151EM/dragongopher/cdc9b1bd1a7752eb.png
  bot-name: Cog2

bundles:
- name: test
  description: A test bundle.
  
  docker:
    image: clockworksoul/relaytest
    tag: latest

  commands:
  - command: splitecho
    description: "Echos back anything sent to it, one parameter at a time."
    executable: [ "/opt/app/splitecho.sh" ]
  - command: curl
    description: "The official curl command."
    executable: [ "/usr/bin/curl" ]
  - command: echo
    description: "Echos back anything sent to it, all at once."
    executable: [ "/bin/echo" ]
