global:
  command-timeout-seconds: 300

docker:
  host: unix:///var/run/docker.sock

slack:
- name: ClockworkSoul
  # No, this isn't a real API token.
  api-token: xoxb-318612539623-512030882149-nyWJ3U4JoWuUtaUkRPKn0dJR
  icon-url: https://emoji.slack-edge.com/T025151EM/dragongopher/cdc9b1bd1a7752eb.png
  bot-name: Cog2

bundles:
- name: test
  description: A test bundle.
  docker:
    image: clockworksoul/relaytest
    tag: latest

  commands:
    splitecho:
      description: "Echos back anything sent to it, one parameter at a time."
      executable: [ "/opt/app/splitecho.sh" ]
    curl:
      description: "The official curl command."
      executable: [ "/usr/bin/curl" ]
    echo:
      description: "Echos back anything sent to it, all at once."
      executable: [ "/bin/echo" ]
