version: '3'

services:
  cog:
    image: clockworksoul/cog2:latest
    command: "/cog2 start -v"
    privileged: true
    ports:
      - "4000:4000"
    volumes:
      - ./test.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cogNetwork

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=cog
      - POSTGRES_PASSWORD="veryKleverPassw0rd!"
      
networks:
  cogNetwork:
