version: '3'

services:
  gort:
    image: clockworksoul/gort:latest
    command: "/gort start -v"
    ports:
      - "4000:4000"
    volumes:
      - ./test.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GORT_DB_PASSWORD=veryKleverPassw0rd
    networks:
      - gort

  postgres:
    image: postgres:13
    # Uncommenting ports lets the database to be inspected with pgAdmin or similar
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=gort
      - POSTGRES_PASSWORD=veryKleverPassw0rd
    networks:
      - gort

networks:
  gort:
