apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gort.fullname" . }}-config
  labels:
    app: {{ template "gort.name" . }}
    chart: {{ template "gort.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yml: |
{{ .Values.config | toYaml | indent 4 }}
