---
gort_bundle_version: 1

name: gort
version: 0.0.1
author: Matt Titmus <matthew.titmus@gmail.com>
homepage: https://getgort.github.io/gort-guide/
description: The default command bundle.
long_description: |-
  The default command bundle, which contains the administrative commands and
  the permissions required to use them.
  Don't change or override this unless you know what you're doing.

permissions:
  - manage_commands
  - manage_groups
  - manage_roles
  - manage_users

docker:
  image: getgort/gort
  tag: {{.Version}}

commands:
  bundle:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "bundle" ]
    rules:
      - must have gort:manage_commands

  group:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "group" ]
    rules:
      - must have gort:manage_groups

  role:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "role" ]
    rules:
      - must have gort:manage_roles

  user:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "user" ]
    rules:
      - must have gort:manage_users

  version:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "version" ]
    rules:
      - allow

  help:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "hidden", "commands" ]
    rules:
      - allow
